### ISSUE TITLE
Plugin Approval

### ISSUE THREAD

**Issue by NyakudyaA** [Klemet/ForestRoadNetworkPluginForQGIS#1]
Please fix the link for the code repository
![Screenshot 2019-08-06 at 07 10 59](https://user-images.githubusercontent.com/2510900/62512721-6f268780-b819-11e9-8d34-bef9ea839411.png)

**Comment by Klemet** [comment]
Hello, NyakudyaA !

My apologies, I did not see the issue. It was due to a "#" character that I forgot to remove in the metadata file of the plugin.

As you can see on https://plugins.qgis.org/plugins/ForestRoadsNetworksUPLOAD/ , this is now fixed.

I'll keep listening if anything else is needed for the approval of the plugin, and I wish you a nice day !
